"""followup action center fields

Revision ID: 36c20e9a53a6
Revises: a9502e18f794
Create Date: 2026-09-12 17:28:18.774231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36c20e9a53a6'
down_revision = 'a9502e18f794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purpose', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('channel', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('document_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_followups_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_followups_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_followups_purpose'), ['purpose'], unique=False)
        batch_op.create_foreign_key("fk_followups_project_id", "client_projects", ["project_id"], ["id"], ondelete="SET NULL")
        batch_op.create_foreign_key("fk_followups_document_id", "documents", ["document_id"], ["id"], ondelete="SET NULL")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followups', schema=None) as batch_op:
        batch_op.drop_constraint("fk_followups_document_id", type_="foreignkey")
        batch_op.drop_constraint("fk_followups_project_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f('ix_followups_purpose'))
        batch_op.drop_index(batch_op.f('ix_followups_project_id'))
        batch_op.drop_index(batch_op.f('ix_followups_document_id'))
        batch_op.drop_column('document_id')
        batch_op.drop_column('project_id')
        batch_op.drop_column('message')
        batch_op.drop_column('channel')
        batch_op.drop_column('purpose')

    # ### end Alembic commands ###
