"""portfolio media vault

Revision ID: 4fd1dfc9f223
Revises: 36c20e9a53a6
Create Date: 2026-09-12 18:17:01.196566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fd1dfc9f223'
down_revision = '36c20e9a53a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('storage', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=2000), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('poster', sa.String(length=2000), nullable=True),
    sa.Column('context', sa.String(length=20), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_media_context'), ['context'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_media_media_type'), ['media_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_media_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_media_visibility'), ['visibility'], unique=False)
        batch_op.create_index('uq_published_intro', ['context'], unique=True, sqlite_where=sa.text("visibility = 'PUBLISHED' AND context = 'INTRO'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_media', schema=None) as batch_op:
        batch_op.drop_index('uq_published_intro', sqlite_where=sa.text("visibility = 'PUBLISHED' AND context = 'INTRO'"))
        batch_op.drop_index(batch_op.f('ix_portfolio_media_visibility'))
        batch_op.drop_index(batch_op.f('ix_portfolio_media_project_id'))
        batch_op.drop_index(batch_op.f('ix_portfolio_media_media_type'))
        batch_op.drop_index(batch_op.f('ix_portfolio_media_context'))

    op.drop_table('portfolio_media')
    # ### end Alembic commands ###
