"""client operations audit trail execution finance

Revision ID: a9502e18f794
Revises: fd2165a84710
Create Date: 2026-09-12 16:22:00.830607

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "a9502e18f794"
down_revision = "fd2165a84710"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "client_projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["client_id"], ["clients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )

    with op.batch_alter_table("client_projects", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_client_projects_client_id"),
            ["client_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_client_projects_status"),
            ["status"],
            unique=False,
        )

    op.create_table(
        "activity_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=True),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["actor_id"], ["admin_users.id"]),
        sa.ForeignKeyConstraint(["client_id"], ["clients.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["client_projects.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    with op.batch_alter_table("activity_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_activity_events_client_id"),
            ["client_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_activity_events_created_at"),
            ["created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_activity_events_event_type"),
            ["event_type"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_activity_events_project_id"),
            ["project_id"],
            unique=False,
        )

    op.create_table(
        "deliverables",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("delivered_at", sa.DateTime(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["client_projects.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    with op.batch_alter_table("deliverables", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_deliverables_project_id"),
            ["project_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_deliverables_status"),
            ["status"],
            unique=False,
        )

    op.create_table(
        "invoices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("invoice_number", sa.String(length=40), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("issued_at", sa.DateTime(), nullable=True),
        sa.Column("due_at", sa.DateTime(), nullable=True),
        sa.Column("paid_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["client_projects.id"],
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    with op.batch_alter_table("invoices", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_invoices_client_id"),
            ["client_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_invoices_invoice_number"),
            ["invoice_number"],
            unique=True,
        )
        batch_op.create_index(
            batch_op.f("ix_invoices_project_id"),
            ["project_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_invoices_status"),
            ["status"],
            unique=False,
        )

    op.create_table(
        "milestones",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["client_projects.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    with op.batch_alter_table("milestones", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_milestones_project_id"),
            ["project_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_milestones_status"),
            ["status"],
            unique=False,
        )

    op.create_table(
        "revision_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("requested_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["client_projects.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    with op.batch_alter_table("revision_requests", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_revision_requests_project_id"),
            ["project_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_revision_requests_status"),
            ["status"],
            unique=False,
        )

    op.create_table(
        "acceptances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("deliverable_id", sa.Integer(), nullable=True),
        sa.Column("acceptance_type", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("accepted_at", sa.DateTime(), nullable=True),
        sa.Column("client_name", sa.String(length=200), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["deliverable_id"],
            ["deliverables.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["client_projects.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    with op.batch_alter_table("acceptances", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_acceptances_acceptance_type"),
            ["acceptance_type"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_acceptances_deliverable_id"),
            ["deliverable_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_acceptances_project_id"),
            ["project_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_acceptances_status"),
            ["status"],
            unique=False,
        )

    op.create_table(
        "document_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("url_or_path", sa.String(length=2000), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("approved_at", sa.DateTime(), nullable=True),
        sa.Column("approved_by_id", sa.Integer(), nullable=True),
        sa.Column("superseded_at", sa.DateTime(), nullable=True),
        sa.Column("superseded_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["approved_by_id"], ["admin_users.id"]),
        sa.ForeignKeyConstraint(["created_by_id"], ["admin_users.id"]),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["superseded_by_id"], ["admin_users.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "document_id",
            "version_number",
            name="uq_doc_version",
        ),
    )

    with op.batch_alter_table("document_versions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_document_versions_document_id"),
            ["document_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_document_versions_status"),
            ["status"],
            unique=False,
        )

    op.create_table(
        "payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("invoice_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("payment_date", sa.DateTime(), nullable=False),
        sa.Column("reference", sa.String(length=200), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_payments_invoice_id"),
            ["invoice_id"],
            unique=False,
        )

    op.create_table(
        "approvals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_version_id", sa.Integer(), nullable=False),
        sa.Column("approval_type", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("approved_at", sa.DateTime(), nullable=True),
        sa.Column("admin_id", sa.Integer(), nullable=True),
        sa.Column("approver_name", sa.String(length=200), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["admin_id"], ["admin_users.id"]),
        sa.ForeignKeyConstraint(
            ["document_version_id"],
            ["document_versions.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    with op.batch_alter_table("approvals", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_approvals_approval_type"),
            ["approval_type"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_approvals_document_version_id"),
            ["document_version_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_approvals_status"),
            ["status"],
            unique=False,
        )

    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("document_number", sa.String(length=40), nullable=True)
        )
        batch_op.add_column(sa.Column("client_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("project_id", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column("current_version_id", sa.Integer(), nullable=True)
        )

        batch_op.create_index(
            batch_op.f("ix_documents_client_id"),
            ["client_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_documents_document_number"),
            ["document_number"],
            unique=True,
        )
        batch_op.create_index(
            batch_op.f("ix_documents_project_id"),
            ["project_id"],
            unique=False,
        )

        batch_op.create_foreign_key(
            "fk_documents_project_id",
            "client_projects",
            ["project_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_foreign_key(
            "fk_documents_client_id",
            "clients",
            ["client_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_foreign_key(
            "fk_documents_current_version",
            "document_versions",
            ["current_version_id"],
            ["id"],
            use_alter=True,
        )

    # Backfill: every pre-existing document gets a number and a v1 row so
    # history is preserved instead of overwritten. New code maintains
    # versions going forward; this only covers legacy rows.

    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute(
            sa.text(
                "UPDATE documents "
                "SET document_number = 'DOC-' || LPAD(id::text, 3, '0') "
                "WHERE document_number IS NULL"
            )
        )
    else:
        op.execute(
            sa.text(
                "UPDATE documents "
                "SET document_number = 'DOC-' || printf('%03d', id) "
                "WHERE document_number IS NULL"
            )
        )

    op.execute(
        sa.text(
            "INSERT INTO document_versions "
            "(document_id, version_number, title, description, url_or_path, "
            "status, created_at) "
            "SELECT id, 1, title, description, url_or_path, status, created_at "
            "FROM documents WHERE id NOT IN "
            "(SELECT document_id FROM document_versions)"
        )
    )

    op.execute(
        sa.text(
            "UPDATE documents SET current_version_id = "
            "(SELECT id FROM document_versions "
            "WHERE document_versions.document_id = documents.id "
            "ORDER BY version_number DESC LIMIT 1) "
            "WHERE current_version_id IS NULL"
        )
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_documents_current_version",
            type_="foreignkey",
        )
        batch_op.drop_constraint(
            "fk_documents_client_id",
            type_="foreignkey",
        )
        batch_op.drop_constraint(
            "fk_documents_project_id",
            type_="foreignkey",
        )
        batch_op.drop_index(batch_op.f("ix_documents_project_id"))
        batch_op.drop_index(batch_op.f("ix_documents_document_number"))
        batch_op.drop_index(batch_op.f("ix_documents_client_id"))
        batch_op.drop_column("current_version_id")
        batch_op.drop_column("project_id")
        batch_op.drop_column("client_id")
        batch_op.drop_column("document_number")

    with op.batch_alter_table("approvals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_approvals_status"))
        batch_op.drop_index(batch_op.f("ix_approvals_document_version_id"))
        batch_op.drop_index(batch_op.f("ix_approvals_approval_type"))

    op.drop_table("approvals")

    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_payments_invoice_id"))

    op.drop_table("payments")

    with op.batch_alter_table("document_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_document_versions_status"))
        batch_op.drop_index(batch_op.f("ix_document_versions_document_id"))

    op.drop_table("document_versions")

    with op.batch_alter_table("acceptances", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_acceptances_status"))
        batch_op.drop_index(batch_op.f("ix_acceptances_project_id"))
        batch_op.drop_index(batch_op.f("ix_acceptances_deliverable_id"))
        batch_op.drop_index(batch_op.f("ix_acceptances_acceptance_type"))

    op.drop_table("acceptances")

    with op.batch_alter_table("revision_requests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_revision_requests_status"))
        batch_op.drop_index(batch_op.f("ix_revision_requests_project_id"))

    op.drop_table("revision_requests")

    with op.batch_alter_table("milestones", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_milestones_status"))
        batch_op.drop_index(batch_op.f("ix_milestones_project_id"))

    op.drop_table("milestones")

    with op.batch_alter_table("invoices", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_invoices_status"))
        batch_op.drop_index(batch_op.f("ix_invoices_project_id"))
        batch_op.drop_index(batch_op.f("ix_invoices_invoice_number"))
        batch_op.drop_index(batch_op.f("ix_invoices_client_id"))

    op.drop_table("invoices")

    with op.batch_alter_table("deliverables", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_deliverables_status"))
        batch_op.drop_index(batch_op.f("ix_deliverables_project_id"))

    op.drop_table("deliverables")

    with op.batch_alter_table("activity_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_activity_events_project_id"))
        batch_op.drop_index(batch_op.f("ix_activity_events_event_type"))
        batch_op.drop_index(batch_op.f("ix_activity_events_created_at"))
        batch_op.drop_index(batch_op.f("ix_activity_events_client_id"))

    op.drop_table("activity_events")

    with op.batch_alter_table("client_projects", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_client_projects_status"))
        batch_op.drop_index(batch_op.f("ix_client_projects_client_id"))

    op.drop_table("client_projects")

    # ### end Alembic commands ###
